app:
  appName: ${APP_NAME}
  envMode: ${ENV_MODE}
  backUrl: ${BACK_URL}
  backUrlDev: ${BACK_URL_DEV}
  backUrlTest: ${BACK_URL_TEST}
  frontUrl: ${FRONT_URL}
  frontUrlDev: ${FRONT_URL_DEV}
  frontUrlTest: ${FRONT_URL_TEST}
  redisUrl: ${REDIS_URL}
  cloudName: ${CLOUD_NAME}
  cloudKey: ${CLOUD_API_KEY}
  cloudSecret: ${CLOUD_API_SECRET}
  weatherApiKey: ${WEATHER_API_KEY}
  dbUrl: ${DB_URL}
  dbUs: ${DB_US}
  dbPwd: ${DB_PWD}
  supabaseCa: ${SUPABASE_CA}

server:
  address: 0.0.0.0
  port: 3000
  tomcat:
    relaxed-query-chars: "[,]"

spring:
  main:
    banner-mode: off

  # ! this way i can send error for routes not found instead
  # ! of trying sending static html
  web:
    resources:
      add-mappings: false

  # ! update it or your images/videos may feel for excess of size
  webflux:
    multipart:
      max-in-memory-size: 50MB
      max-disk-usage-per-part: 100MB

  r2dbc:
    url: ${generated_on_boot}
    username: ${generated_on_boot}
    password: ${generated_on_boot}
    pool:
      enabled: true
      initial-size: 0
      max-size: 20
      max-acquire-time: 240s
      validation-query: SELECT 1

  liquibase:
    enabled: true
    change-log: classpath:sql/master.yml

logging:
  level:
    root: WARN
